const CREATE_STREAM = 'CREATE_STREAM';
const DESTROY_STREAM = 'DESTROY_STREAM';
const EDIT_STREAM = 'EDIT_STREAM';
const INDEX_STREAMS = 'INDEX_STREAMSS';
const SHOW_STREAM = 'SHOW_STREAM';
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';

export {
  CREATE_STREAM,
  DESTROY_STREAM,
  EDIT_STREAM,
  INDEX_STREAMS,
  SHOW_STREAM,
  SIGN_IN,
  SIGN_OUT
};
